### ISSUE TITLE
Autenticação

### ISSUE THREAD

**Issue by adzubla** [OpenInsurance-Brasil/areadesenvolvedor#12]
A documentação faz referencia a autenticação no item abaixo:
https://openinsurance-brasil.github.io/areadesenvolvedor/#authentication

Mas o meu entendimento da "fase open data" é que todas as apis de Canais e Produtos são públicas e não há necessidade de autenticação. Correto?

**Comment by adzubla** [comment]
No arquivo `open_data_products_services.yaml` tambem existe uma definição de segurança desnecessária: 
```
securitySchemes:
  OpenId:
    type: openIdConnect
    openIdConnectUrl: 'https://auth.mockbank.poc.raidiam.io/.well-known/openid-configuration'
  OAuth2Security:
```
