### ISSUE TITLE
Em ResponseCapitalizationTitleList o objeto "brand" deveria estar dentro de "data"

### ISSUE THREAD

**Issue by adzubla** [OpenInsurance-Brasil/areadesenvolvedor#26]
Em ResponseCapitalizationTitleList o objeto "brand" deveria estar dentro de "data"

Atualmente está assim: 
```
    ResponseCapitalizationTitleList:
      type: object
      required:
        - data
        - brand
        - links
        - meta
```
